import type { NextConfig } from "next";

const NEW = "https://www.thenycmarketingcompany.com";

const nextConfig: NextConfig = {
  async redirects() {
    return [
      // ── URL restructure (old short routes → correct new-domain paths) ──
      { source: "/industries", destination: `${NEW}/industries-we-offer-marketing-services-for`, permanent: true },
      { source: "/areas", destination: `${NEW}/services-areas-we-offer-marketing-services-in`, permanent: true },
      { source: "/free-seo-audit", destination: `${NEW}/the-free-human%2Bai-seo-marketing-review`, permanent: true },
      { source: "/marketing-checklist-2026", destination: `${NEW}/master-marketing-checklist-last-updated-2026`, permanent: true },
      { source: "/roi-calculator", destination: `${NEW}/annual-marketing-spend-roi-calculator`, permanent: true },
      { source: "/blog", destination: `${NEW}/the-marketing-blog`, permanent: true },
      { source: "/ai", destination: `${NEW}/artificial-intelligence-marketing-services-offered`, permanent: true },
      { source: "/blog/:path*", destination: `${NEW}/the-marketing-blog/:path*`, permanent: true },
      { source: "/industries/:path*", destination: `${NEW}/industries-we-offer-marketing-services-for/:path*`, permanent: true },

      // ── Old category/breadcrumb routes ──
      { source: "/Web Design", destination: `${NEW}/services/web-design-nyc`, permanent: true },
      { source: "/Web%20Design", destination: `${NEW}/services/web-design-nyc`, permanent: true },
      { source: "/Branding", destination: `${NEW}/services/brand-strategy-identity-in-nyc`, permanent: true },
      { source: "/Strategy", destination: `${NEW}/services/business-strategy-consulting-in-nyc`, permanent: true },
      { source: "/Services", destination: `${NEW}/services`, permanent: true },
      { source: "/Services/SEO", destination: `${NEW}/services/search-engine-optimization-seo-nyc`, permanent: true },
      { source: "/Services/SEO/:path*", destination: `${NEW}/services/search-engine-optimization-seo-nyc`, permanent: true },
      { source: "/Content%20Marketing", destination: `${NEW}/services/content-marketing-in-nyc`, permanent: true },
      { source: "/Content Marketing", destination: `${NEW}/services/content-marketing-in-nyc`, permanent: true },
      { source: "/More", destination: `${NEW}/`, permanent: true },
      { source: "/More/Service%20Areas", destination: `${NEW}/services-areas-we-offer-marketing-services-in`, permanent: true },
      { source: "/More/Service Areas", destination: `${NEW}/services-areas-we-offer-marketing-services-in`, permanent: true },

      // ── Old service sub-pages → new service slugs ──
      { source: "/services/web-design", destination: `${NEW}/services/web-design-nyc`, permanent: true },
      { source: "/services/website-design", destination: `${NEW}/services/website-design-in-nyc`, permanent: true },
      { source: "/services/mobile-responsive-web-design", destination: `${NEW}/services/mobile-responsive-web-design-in-nyc`, permanent: true },
      { source: "/services/website-optimization", destination: `${NEW}/services/website-optimization-in-nyc`, permanent: true },
      { source: "/services/landing-page-design", destination: `${NEW}/services/landing-page-design-in-nyc`, permanent: true },
      { source: "/services/micro-site-website-design", destination: `${NEW}/services/micro-site-website-design-in-nyc`, permanent: true },
      { source: "/services/seo", destination: `${NEW}/services/search-engine-optimization-seo-nyc`, permanent: true },
      { source: "/services/seo-services", destination: `${NEW}/services/seo-services-in-nyc`, permanent: true },
      { source: "/services/local-seo", destination: `${NEW}/services/local-seo-in-nyc`, permanent: true },
      { source: "/services/technical-seo", destination: `${NEW}/services/technical-seo-in-nyc`, permanent: true },
      { source: "/services/on-page-seo", destination: `${NEW}/services/on-page-seo-optimization-in-nyc`, permanent: true },
      { source: "/services/on-page-seo-optimization", destination: `${NEW}/services/on-page-seo-optimization-in-nyc`, permanent: true },
      { source: "/services/off-page-seo", destination: `${NEW}/services/off-page-seo-and-link-building-in-nyc`, permanent: true },
      { source: "/services/keyword-research", destination: `${NEW}/services/keyword-research-and-strategy-in-nyc`, permanent: true },
      { source: "/services/keyword-research-and-strategy", destination: `${NEW}/services/keyword-research-and-strategy-in-nyc`, permanent: true },
      { source: "/services/seo-audit", destination: `${NEW}/services/seo-audit-and-analysis-in-nyc`, permanent: true },
      { source: "/services/seo-audit-and-analysis", destination: `${NEW}/services/seo-audit-and-analysis-in-nyc`, permanent: true },
      { source: "/services/logo-design", destination: `${NEW}/services/logo-design-in-nyc`, permanent: true },
      { source: "/services/brand-naming", destination: `${NEW}/services/brand-naming-and-rebranding-in-nyc`, permanent: true },
      { source: "/services/brand-naming-and-rebranding", destination: `${NEW}/services/brand-naming-and-rebranding-in-nyc`, permanent: true },
      { source: "/services/branding", destination: `${NEW}/services/brand-strategy-identity-in-nyc`, permanent: true },
      { source: "/services/content-marketing", destination: `${NEW}/services/content-marketing-in-nyc`, permanent: true },
      { source: "/services/video-content-production", destination: `${NEW}/services/video-content-production-in-nyc`, permanent: true },
      { source: "/services/content-strategy", destination: `${NEW}/services/content-strategy-and-planning-in-nyc`, permanent: true },
      { source: "/services/content-strategy-and-planning", destination: `${NEW}/services/content-strategy-and-planning-in-nyc`, permanent: true },
      { source: "/services/social-media", destination: `${NEW}/services/social-media-marketing-in-nyc`, permanent: true },
      { source: "/services/social-media-management", destination: `${NEW}/services/social-media-management-in-nyc`, permanent: true },
      { source: "/services/social-media-marketing", destination: `${NEW}/services/social-media-marketing-in-nyc`, permanent: true },
      { source: "/services/social-media-marketing-strategy", destination: `${NEW}/services/social-media-marketing-strategy-in-nyc`, permanent: true },
      { source: "/services/social-media-advertising", destination: `${NEW}/services/social-media-advertising-in-nyc`, permanent: true },
      { source: "/services/social-media-content-creation", destination: `${NEW}/services/social-media-content-creation-in-nyc`, permanent: true },
      { source: "/services/ppc-advertising", destination: `${NEW}/services/ppc-advertising-in-nyc`, permanent: true },
      { source: "/services/ppc", destination: `${NEW}/services/digital-advertising-ppc-in-nyc`, permanent: true },
      { source: "/services/paid-search-campaigns", destination: `${NEW}/services/paid-search-campaigns-in-nyc`, permanent: true },
      { source: "/services/google-ads", destination: `${NEW}/services/google-ads-management-in-nyc`, permanent: true },
      { source: "/services/email-marketing", destination: `${NEW}/services/email-marketing-automation-in-nyc`, permanent: true },
      { source: "/services/email-marketing-campaigns", destination: `${NEW}/services/email-marketing-campaigns-in-nyc`, permanent: true },
      { source: "/services/email-campaign-management", destination: `${NEW}/services/email-campaign-management-in-nyc`, permanent: true },
      { source: "/services/marketing-automation", destination: `${NEW}/services/marketing-automation-in-nyc`, permanent: true },
      { source: "/services/drip-campaigns", destination: `${NEW}/services/drip-campaigns-and-nurture-sequences-in-nyc`, permanent: true },
      { source: "/services/drip-campaigns-and-nurture-sequences", destination: `${NEW}/services/drip-campaigns-and-nurture-sequences-in-nyc`, permanent: true },
      { source: "/services/online-reputation-management", destination: `${NEW}/services/online-reputation-management-in-nyc`, permanent: true },
      { source: "/services/online-reputation", destination: `${NEW}/services/online-reputation-management-in-nyc`, permanent: true },
      { source: "/services/press-release", destination: `${NEW}/services/press-release-writing-and-distribution-in-nyc`, permanent: true },
      { source: "/services/press-release-writing-and-distribution", destination: `${NEW}/services/press-release-writing-and-distribution-in-nyc`, permanent: true },
      { source: "/services/media-outreach", destination: `${NEW}/services/media-outreach-in-nyc`, permanent: true },
      { source: "/services/digital-pr-campaigns", destination: `${NEW}/services/digital-pr-campaigns-in-nyc`, permanent: true },
      { source: "/services/digital-pr", destination: `${NEW}/services/digital-pr-campaigns-in-nyc`, permanent: true },
      { source: "/services/public-relations", destination: `${NEW}/services/public-relations-reputation-in-nyc`, permanent: true },
      { source: "/services/google-analytics", destination: `${NEW}/services/google-analytics-setup-and-management-in-nyc`, permanent: true },
      { source: "/services/google-analytics-setup-and-management", destination: `${NEW}/services/google-analytics-setup-and-management-in-nyc`, permanent: true },
      { source: "/services/marketing-technology-consulting", destination: `${NEW}/services/marketing-technology-consulting-in-nyc`, permanent: true },
      { source: "/services/performance-tracking", destination: `${NEW}/services/performance-tracking-and-kpis-in-nyc`, permanent: true },
      { source: "/services/performance-tracking-and-kpis", destination: `${NEW}/services/performance-tracking-and-kpis-in-nyc`, permanent: true },
      { source: "/services/analytics", destination: `${NEW}/services/analytics-technology-in-nyc`, permanent: true },
      { source: "/services/business-growth-consulting", destination: `${NEW}/services/business-growth-consulting-in-nyc`, permanent: true },
      { source: "/services/swot-analysis", destination: `${NEW}/services/swot-analysis-in-nyc`, permanent: true },
      { source: "/services/strategic-business-planning", destination: `${NEW}/services/strategic-business-planning-in-nyc`, permanent: true },
      { source: "/services/scaling-and-expansion-strategy", destination: `${NEW}/services/scaling-and-expansion-strategy-in-nyc`, permanent: true },
      { source: "/services/influencer-marketing", destination: `${NEW}/services/influencer-marketing-in-nyc`, permanent: true },

      // ── Old area routes ──
      { source: "/nyc-marketing-company-service-areas", destination: `${NEW}/services-areas-we-offer-marketing-services-in`, permanent: true },
      { source: "/areas/bronx", destination: `${NEW}/services-areas-we-offer-marketing-services-in/bronx-marketing-company`, permanent: true },
      { source: "/areas/brooklyn", destination: `${NEW}/services-areas-we-offer-marketing-services-in/brooklyn-marketing-company`, permanent: true },
      { source: "/areas/queens", destination: `${NEW}/services-areas-we-offer-marketing-services-in/queens-marketing-company`, permanent: true },
      { source: "/areas/manhattan", destination: `${NEW}/services-areas-we-offer-marketing-services-in/manhattan-marketing-company`, permanent: true },
      { source: "/areas/staten-island", destination: `${NEW}/services-areas-we-offer-marketing-services-in/staten-island-marketing-company`, permanent: true },
      { source: "/areas/long-island", destination: `${NEW}/services-areas-we-offer-marketing-services-in/long-island-marketing-company`, permanent: true },
      { source: "/areas/westchester", destination: `${NEW}/services-areas-we-offer-marketing-services-in/westchester-marketing-company`, permanent: true },
      { source: "/areas/:path*", destination: `${NEW}/services-areas-we-offer-marketing-services-in/:path*`, permanent: true },

      // ── Old /service-areas/ links (pre-rebrand) ──
      { source: "/service-areas/nyc-digital-marketing-agency", destination: `${NEW}/services-areas-we-offer-marketing-services-in/manhattan-marketing-company`, permanent: true },
      { source: "/service-areas/queens-digital-marketing-agency", destination: `${NEW}/services-areas-we-offer-marketing-services-in/queens-marketing-company`, permanent: true },
      { source: "/service-areas/brooklyn-digital-marketing-agency", destination: `${NEW}/services-areas-we-offer-marketing-services-in/brooklyn-marketing-company`, permanent: true },
      { source: "/service-areas/long-island-digital-marketing-agency", destination: `${NEW}/services-areas-we-offer-marketing-services-in/long-island-marketing-company`, permanent: true },
      { source: "/service-areas/hoboken-digital-marketing-agency", destination: `${NEW}/services-areas-we-offer-marketing-services-in/hoboken-marketing-company`, permanent: true },
      { source: "/service-areas/:path*", destination: `${NEW}/services-areas-we-offer-marketing-services-in`, permanent: true },

      // ── Old misc pages ──
      { source: "/services", destination: `${NEW}/nyc-marketing-company-services-list`, permanent: true },
      { source: "/marketing-101", destination: `${NEW}/nyc-marketing-101-guide`, permanent: true },
      { source: "/nyc-digital-marketing-agency-services-offered-by-consortium-nyc", destination: `${NEW}/nyc-marketing-company-services-list`, permanent: true },
      { source: "/nyc-digital-marketing-agency", destination: `${NEW}/`, permanent: true },
      { source: "/nyc-digital-marketing-agency/:path*", destination: `${NEW}/`, permanent: true },
      { source: "/nyc-digital-marketing-agency-faqs", destination: `${NEW}/nyc-marketing-company-faqs`, permanent: true },
      { source: "/about-digital-marketing-agency", destination: `${NEW}/about`, permanent: true },
      { source: "/pricing", destination: `${NEW}/nyc-marketing-pricing-guide`, permanent: true },
      { source: "/faq", destination: `${NEW}/nyc-marketing-company-faqs`, permanent: true },
      { source: "/faqs", destination: `${NEW}/nyc-marketing-company-faqs`, permanent: true },
      { source: "/portfolio", destination: `${NEW}/nyc-marketing-company-portfolio`, permanent: true },
      { source: "/contact-nyc-marketing-company", destination: `${NEW}/contact`, permanent: true },

      // ── Catch-all: 301 every remaining page 1:1 to new domain ──
      { source: "/:path*", destination: `${NEW}/:path*`, permanent: true },
    ];
  },
};

export default nextConfig;
